<script>
  import logo from './assets/svelte.png'
  import Counter from './lib/Counter.svelte'

  let name = "";
  let greeting = "";

  function greet() {
    window.go.main.App.Greet(name).then((result) => {
      greeting = result;
    });
  }
</script>

<main>
  <img src={logo} alt="Svelte Logo" />
  <h1>
    Hello world!
  </h1>

  <Counter />

  <p>
    Visit <a href="https://svelte.dev">svelte.dev</a> to learn how to build Svelte
    apps.
  </p>

  <p>
    Check out <a href="https://github.com/sveltejs/kit#readme">SvelteKit</a> for
    the officially supported framework, also powered by Vite!
  </p>

  <hr>

  <p>This tests that the Go functionality is working too. The greeting is generated by Go.</p>
  <div id="input" data-wails-no-drag>
    <input id="name" type="text" bind:value={name}>
    <button class="button" on:click={greet}>Greetings</button>
  </div>
  {#if greeting}
    <div id="result">{greeting}</div>
  {/if}
</main>

<style>
  :root {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen,
      Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
  }

  main {
    text-align: center;
    padding: 1em;
    margin: 0 auto;
  }

  img {
    height: 16rem;
    width: 16rem;
  }

  h1 {
    @apply text-3xl font-bold underline text-emerald-700;
    /*color: #ff3e00;
    text-transform: uppercase;
    font-size: 4rem;
    font-weight: 100;*/
    line-height: 1.1;
    margin: 2rem auto;
    max-width: 14rem;
  }

  p {
    max-width: 14rem;
    margin: 1rem auto;
    line-height: 1.35;
  }

  @media (min-width: 480px) {
    h1 {
      max-width: none;
    }

    p {
      max-width: none;
    }
  }
</style>
